version: '3.8'

services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - monitoring-network
    environment:
      - HOST=localhost
      - PORT=8080
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
      labels:
        - "service.name=visualizer"
        - "service.type=monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    hostname: '{{.Node.Hostname}}'
    ports:
      - "8082:8080"
    networks:
      - monitoring-network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global  # Un cadvisor par nœud
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
      labels:
        - "service.name=cadvisor"
        - "service.type=monitoring"

  portainer-agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - monitoring-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
          cpus: '0.3'
      labels:
        - "service.name=portainer-agent"
        - "service.type=monitoring"

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - monitoring-network
    volumes:
      - portainer-data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
      labels:
        - "service.name=portainer"
        - "service.type=monitoring"

  node-exporter:
    image: prom/node-exporter:latest
    hostname: '{{.Node.Hostname}}'
    ports:
      - "9100:9100"
    networks:
      - monitoring-network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
          cpus: '0.3'
        reservations:
          memory: 64M
          cpus: '0.1'
      labels:
        - "service.name=node-exporter"
        - "service.type=monitoring"

networks:
  monitoring-network:
    driver: overlay
    attachable: true
    labels:
      - "network.name=monitoring-network"
      - "network.description=Network for monitoring services"

volumes:
  portainer-data:
    driver: local
    labels:
      - "volume.name=portainer-data"
      - "volume.description=Portainer persistent data"