version: '3.8'

services:
  api:
    image: swarm-api:latest
    build:
      context: ../applications/api
      dockerfile: Dockerfile
    networks:
      - web-network
    environment:
      - NODE_ENV=production
      - SERVICE_NAME=api
      - SERVICE_VERSION=1.0.0
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
      labels:
        - "service.name=api"
        - "service.type=backend"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-app:
    image: swarm-webapp:latest
    build:
      context: ../applications/web-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - web-network
    depends_on:
      - api
    environment:
      - SERVICE_NAME=web-app
      - SERVICE_VERSION=1.0.0
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      placement:
        constraints:
          - node.role != manager  # Peut tourner sur workers ou managers non-leader
      resources:
        limits:
          memory: 128M
          cpus: '0.3'
        reservations:
          memory: 64M
          cpus: '0.1'
      labels:
        - "service.name=web-app"
        - "service.type=frontend"
        - "traefik.enable=true"
        - "traefik.http.routers.webapp.rule=Host(`webapp.local`)"
        - "traefik.http.services.webapp.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  web-network:
    driver: overlay
    attachable: true
    labels:
      - "network.name=web-network"
      - "network.description=Network for web application stack"

configs:
  nginx_config:
    file: ../applications/web-app/nginx.conf
    labels:
      - "config.name=nginx"
      - "config.version=1.0"